### ISSUE TITLE
Multiple prompts show  on first question every time 

### ISSUE THREAD

**Issue by sdnorm** [SuperDupr/builder#100]
AND the functionality is off. 

1. First question always shows the arrow to go to the second prompt even when there isn't one. 
![Screenshot 2023-09-11 at 10 47 48 AM](https://github.com/SuperDupr/builder/assets/4260841/b4bb1b21-3b52-4c8f-8587-ca3c4a9f4587)

2. Arrow disappear when you go the phantom second prompt on the first question. 
![Screenshot 2023-09-11 at 10 50 20 AM](https://github.com/SuperDupr/builder/assets/4260841/fce84ba4-789e-4fe8-952b-65c44638779f)

**Comment by Moiz1524** [comment]
@imranhayat Please watch out for this!
