### ISSUE TITLE
Is there a plan to make a view for teams that shows the users on each?

### ISSUE THREAD

**Issue by sdnorm** [SuperDupr/builder#40]

**Comment by Moiz1524** [comment]
Yes, I have this thought inside my mind. Kind of an extended breakdown of team's users. Let me know if this needs to be incorporated with phase#2 or if should we delay it to some extent! Please add appropriate label afterwards!

**Comment by sdnorm** [comment]
I think this would help give the client a better UX with the dashboard so the sooner the better to implemented. What label should I apply?

**Comment by Moiz1524** [comment]
PR with tag number is generated!
