### ISSUE TITLE
Masquerading

### ISSUE THREAD

**Issue by sdnorm** [SuperDupr/builder#41]
Since we are customizing the Administrate views I see that we don't have a full `users` table yet. Which also takes away from the ability to masquerade as users. We would like to keep that ability. Useful for development and customer service going forward.

**Comment by Moiz1524** [comment]
Sure. Let me know if this needs to be incorporated with phase#2 or if should we delay it to some extent!. Please add appropriate label afterwards

**Comment by sdnorm** [comment]
I think that it would be good to add to phase 2. Let me know if it more of a lift than I am expecting. The capability is there just need to make it available on the current Super Admin Dash.

**Comment by Moiz1524** [comment]
We are doing it today!

**Comment by Moiz1524** [comment]
PR with tag number is generated!
