### ISSUE TITLE
remove links in org settings section for org members 

### ISSUE THREAD

**Issue by sdnorm** [SuperDupr/builder#56]
Only show the team that member is on

**Comment by sdnorm** [comment]
If the user doesn't have access to the link, the link should be removed. 

https://github.com/SuperDupr/builder/assets/4260841/ccfed0d5-60d0-42ec-bccf-19254aaf55af

I think an Org Member can see the teams, but only see the teams. So the `Teams` link can stay but the options to edit, etc need to be removed for Org Members. 

![image](https://github.com/SuperDupr/builder/assets/4260841/ea5e0e88-aee1-46eb-bd01-9c08c6ad456a)

**Comment by Moiz1524** [comment]
Got it. I'm taking this inside my backlog

**Comment by Moiz1524** [comment]
This has been done inside be_story_building_organization
