### ISSUE TITLE
need a way for a users team to be updated, org admin ability

### ISSUE THREAD

**Issue by sdnorm** [SuperDupr/builder#57]

**Comment by Moiz1524** [comment]
@sdnorm I need more context around it. Can you please provide? So I can take care of this in the next sprint!

**Comment by sdnorm** [comment]
Where can an Org Admin currently change the team that a member is on? 

I think ideally it would be on this page with an `edit` option for each user. 

![image](https://github.com/SuperDupr/builder/assets/4260841/773c9051-2d2d-49a9-9786-a44c1d5db617)

**Comment by Moiz1524** [comment]
Got it. You are talking about changing the team of a user. I'm taking this inside my backlog!

**Comment by Moiz1524** [comment]
Its done.
[PR](https://github.com/SuperDupr/builder/pull/109)
