### ISSUE TITLE
remove "Login As" from Org. Admin dashboard user list

### ISSUE THREAD

**Issue by sdnorm** [SuperDupr/builder#84]
![image](https://github.com/SuperDupr/builder/assets/4260841/8c1dc195-9d0b-4602-be03-7b244c864bbf)

**Comment by Moiz1524** [comment]
@sdnorm This has been fixed!

**Comment by sdnorm** [comment]
@Moiz1524 Not sure what happened but the `login as` button has reappeared on the dashboard for an Org Admin. 

![image](https://github.com/SuperDupr/builder/assets/4260841/3c176b47-51f4-4748-8637-de6b05a81bf6)
