### ISSUE TITLE
make the "Add Question" for building builders more of a button

### ISSUE THREAD

**Issue by sdnorm** [SuperDupr/builder#85]
Or something to make it more obvious that is an action to take. 

![image](https://github.com/SuperDupr/builder/assets/4260841/60186ecd-1936-465b-81d5-12267fae17d2)

**Comment by Moiz1524** [comment]
@imranhayat Please follow-up for this week!

**Comment by Moiz1524** [comment]
@sdnorm This has been fixed and merged inside `be_story_building_organization` branch
