### ISSUE TITLE
Add New Prompt isn't working

### ISSUE THREAD

**Issue by sdnorm** [SuperDupr/builder#86]
![image](https://github.com/SuperDupr/builder/assets/4260841/3cdbd44c-a23b-4211-b352-f2d404b8353c)

**Comment by sdnorm** [comment]
These aren't working either.

![image](https://github.com/SuperDupr/builder/assets/4260841/6079e462-ce4b-40fc-ba17-c437c74cb0d0)

**Comment by Moiz1524** [comment]
@sdnorm This has been fixed and pushed onto be_story_building_superadmin and be_story_building_organization branches

**Comment by sdnorm** [comment]
@Moiz1524 as I noted on the `Login As` issue, this seems to have been reversed as well.
